name: Vipani Frontend S3 Upload

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1 # downloads node and npm
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: CI=true npm run build

    - name: Assume IAM Role
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: GitHubActions

    - name: Sync to S3
      run: aws s3 sync ./build s3://vipaniai
      
    - name: Create invalidation for Cloudfront distribution
      run: aws cloudfront create-invalidation --distribution-id E1YB4YGPK9CBAD --paths "/*"
