
const base_url = "https://api.staging.vipaniai.com/api/";
// const mock_api = "https://67c9191b0acf98d07088c2e3.mockapi.io/vipani-mock-api/";
const API ={
  base_url: "https://api.staging.vipaniai.com/api/",
  user_login: `${base_url}login`,
  admin_login:`${base_url}admin/user-login`,
  forgot_password: `${base_url}forgot-password`,
  reset_password:`${base_url}reset-password`,
  refresh_token:`${base_url}refresh-token`,
  profile:`${base_url}profile`,
  change_2FA:`${base_url}toggle-2fa`,
  change_password:`${base_url}profile/change-password`,
  getEmployeeData:`${base_url}employees`,
  get_retention_rate:`${base_url}retention-rate`,
  get_turnover_rate:`${base_url}turnover-rate`,
  get_revenue_pre_employee:`${base_url}revenue-per-employee`,
  get_internal_mobility_rate:`${base_url}internal-mobility-rate`,
  get_departments:`${base_url}departments`,
  get_locations:`${base_url}locations`,
  get_absenteeism_rate: `${base_url}absenteeism-rate`,
  get_absenteeism_cost:`${base_url}absenteeism-cost`,
  get_turnover_cost:`${base_url}turn-over-cost`,
  get_performace_deficit_impact: `${base_url}pdi`,
  get_cost_of_vacancy:`${base_url}costOfVacancy`,
  get_first_year_retention_rate: `${base_url}first-year-retention-rate`,
  get_organization_chart_data: `${base_url}departments/hierarchy`,
  save_report_data:`${base_url}reports/save`,
  get_reports_data: `${base_url}reports/get`,
  get_report_recommendatation: `${base_url}report_recommendatation`,
  star_report: `${base_url}reports/star`,
  delete_report: `${base_url}reports/delete-multiple`,
  add_report_comment: `${base_url}reports/post-comment`,
  get_report_comment: `${base_url}reports/get-comments`,
  post_key_report_comment: `${base_url}key-reports/comment`,
  get_key_report_comment: `${base_url}key-reports/get-comments`,
  post_overview_key_report_comment:`${base_url}key-reports/save-comment`,
  get_overview_key_report_comment:`${base_url}key-report-get-overview-comments`,
  get_location_matrics: `${base_url}locations/metrics`,
  add_step_engagement: `${base_url}add-step`,
  get_engagement: `${base_url}engagment-api`,
  update_engagement_notes: `${base_url}update-engagement-notes`,
  leave_feedback:`${base_url}notes/feedback`,
  get_engagement_assigned_task: `${base_url}engagement/assign-to/get`,
  engagement_assign_task: `${base_url}engagements/assign-task`,
  share_report: `${base_url}reports/share`,
  add_user: `${base_url}add-user`,
  get_users:`${base_url}get-users`,
  delete_user:`${base_url}delete-user`,
  send_reminder: `${base_url}send-reminder-monitor`,
  getCompanyPerformanceData: "./companyPerformance.json",
  getReportsData: "../reports.json",
  getFinancialImpactData: "./financialImpact.json",
  getSettingsData: "./settings.json",
  getCompanyPerformancePredictiveAnalyticsData: "../companyPerformancePredictiveAnalytics.json",
  getFinancialImpactPredictiveAnalyticsData: "../financialImpactPredictiveAnalytics.json",
}

export default API;